#!/bin/bash

BUILD_CONFIGS="${@}"

# guarantee some basic exported stuffs
if [ "${ARCH}" != "arm" ] ; then
	export ARCH="arm"
	echo "ARCH has been set to \"${ARCH}\""
fi
if [ "${HOST_PLATFORM}" != "zoom2" ] ; then
	export HOST_PLATFORM="zoom2"
	echo "HOST_PLATFORM has been set to \"${HOST_PLATFORM}\""
fi
if [ -z "${KERNEL_DIR}" ] ; then
	export KERNEL_DIR="$(cd "$(dirname "${0}")/../"; pwd)"
	echo "KERNEL_DIR has been set to \"${KERNEL_DIR}\""
fi
if [ -z "${CROSS_COMPILE}" ] ; then
	export CROSS_COMPILE="arm-eabi-"
	echo "CROSS_COMPILE has been set to \"${CROSS_COMPILE}\""
fi

# ensure some android build stuff has been defined
if [ -z "${ANDROID_BUILD_TOP}" ] ; then
	echo "you must run build/envsetup.sh as well as lunch, to set some android envs"
	exit 1
else
	echo "ANDROID_BUILD_TOP was found to be \"${ANDROID_BUILD_TOP}\""
fi

REQUIRED_PROPS="etc/wifi/fw_wlan1271.bin \
		etc/wifi/tiwlan.ini"

# we now perform a few contingency checks (make sure some props are available that we need)
for prop in ${REQUIRED_PROPS} ; do
	if [ ! -f "${ANDROID_BUILD_TOP}/device/motorola/sholes/proprietary/$(basename "${prop}")" ] ; then
		echo "Failed to locate a required proprietary file: ${prop}"
		exit 1
	fi
done

olddir="$(pwd)"

if [ -z "${BUILD_CONFIGS}" ] ; then
	BUILD_CONFIGS=$(ls -1 "${KERNEL_DIR}"/arch/arm/configs/*sapphire*_defconfig | sed -r "s/^.*\/([^\/]+)$/\1/")
fi

for i in ${BUILD_CONFIGS}; do
	# verify the config exists
	if [ ! -f "${KERNEL_DIR}/arch/arm/configs/${i}" ] ; then
		echo "The specified config [${i}] could not be found.  Skipping..."
		continue
	fi

	echo "Building ${i} ..."

	# move to the kernel directory
	cd "${KERNEL_DIR}"

	# clean the tree
	make mrproper

	# load the config
	make "${i}"

	# make the kernel/modules
	make -j4

	# create an output directory
	rm -fr tmpdir
	mkdir tmpdir

	# copy the kernel image
	cp arch/arm/boot/zImage tmpdir/
	# copy all of the modules to that directory
	for j in $(find . -name "*.ko"); do
		cp "${j}" tmpdir/
	done

	# now we go make our wireless module
	cd "${ANDROID_BUILD_TOP}/system/wlan/ti/wilink_6_1/platforms/os/linux"
	# clean an existing wireless module
	make clean
	# make the module
	make
	# copy it to our output
	cp tiwlan_drv.ko "${KERNEL_DIR}/tmpdir/"

	# return to the kernel directory
	cd "${KERNEL_DIR}"

	# now we begin to build our anykernel

	# copy the anykernel stuff
	cp -a anykernel.tpl tmpdir/anykernel
	# ensure needed directories are there
	mkdir -p tmpdir/anykernel/kernel
	mkdir -p tmpdir/anykernel/system/lib/modules
	# put the kernel in the right spot
	cp tmpdir/zImage tmpdir/anykernel/kernel
	# copy all of our modules
	for j in tmpdir/*.ko; do
		cp "${j}" tmpdir/anykernel/system/lib/modules/
	done

	# copy any required props
	for prop in ${REQUIRED_PROPS} ; do
		mkdir -p "tmpdir/anykernel/system/$(dirname "${prop}")"
		cp "${ANDROID_BUILD_TOP}/device/motorola/sholes/proprietary/$(basename "${prop}")" "tmpdir/anykernel/system/${prop}"
	done

	# zip the file
	cd tmpdir/anykernel
	zip -r "${KERNEL_DIR}/${i}.zip" .
	cd "${KERNEL_DIR}"

	# move back to the old directory
	cd "${olddir}"
done
